{
 "title": "8000 Peering Telemetry Dashboard",
 "time": { "from": "2023-11-30T23:00:00.000Z", "to": "2023-12-22T22:59:59.000Z" },
 "panels": [
  {
   "title": "BGP Flowspec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dropped Attacks(bps)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "Dropped pps Flow [[tag_flow_notation]]",
       "groupBy": [
        { "params": [ "flow_notation" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-flowspec-oper:flow-spec/vrfs/vrf/afs/af/flows/flow",
       "select": [
        [
         { "params": [ "flow_statistics/dropped/bytes" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "* 8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" }
       ]
      }
     ]
    },
    {
     "title": "Attacks Mitigation (pps)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "alias": "Dropped pps Flow [[tag_flow_notation]]",
       "groupBy": [
        { "params": [ "flow_notation" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-flowspec-oper:flow-spec/vrfs/vrf/afs/af/flows/flow",
       "select": [
        [
         {
          "params": [
           "flow_statistics/dropped/packets"
          ],
          "type": "field"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" }
       ]
      }
     ]
    },
    {
     "title": "Number of Active BGP FS Rules",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-flowspec-oper:flow-spec/summary",
       "select": [
        [
         { "params": [ "flows" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Netflow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Export Statistics (pps)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "alias": "Packets exported",
       "measurement": "Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter",
       "select": [
        [
         {
          "params": [
           "statistic/collector/packets_sent"
          ],
          "type": "field"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "exporter_name", "operator": "=", "value": "NF-EXPORT" }
       ]
      },
      {
       "alias": "Flows exported",
       "measurement": "Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter",
       "select": [
        [
         { "params": [ "statistic/collector/flows_sent" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "exporter_name", "operator": "=", "value": "NF-EXPORT" }
       ]
      },
      {
       "alias": "Templates exported",
       "measurement": "Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter",
       "select": [
        [
         {
          "params": [
           "statistic/collector/option_templates_sent"
          ],
          "type": "field"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "exporter_name", "operator": "=", "value": "NF-EXPORT" }
       ]
      },
      {
       "alias": "Option data exported",
       "measurement": "Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter",
       "select": [
        [
         {
          "params": [
           "statistic/collector/option_data_sent"
          ],
          "type": "field"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "exporter_name", "operator": "=", "value": "NF-EXPORT" }
       ]
      },
      {
       "alias": "Option templates exported",
       "measurement": "Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter",
       "select": [
        [
         {
          "params": [
           "statistic/collector/option_templates_sent"
          ],
          "type": "field"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "exporter_name", "operator": "=", "value": "NF-EXPORT" }
       ]
      }
     ]
    },
    {
     "title": "Export Statistics (dropped packets)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "alias": "Flows dropped",
       "measurement": "Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter",
       "select": [
        [
         {
          "params": [
           "statistic/collector/flows_dropped"
          ],
          "type": "field"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "exporter_name", "operator": "=", "value": "NF-EXPORT" }
       ]
      },
      {
       "alias": "Templates dropped",
       "measurement": "Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter",
       "select": [
        [
         {
          "params": [
           "statistic/collector/templates_dropped"
          ],
          "type": "field"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "exporter_name", "operator": "=", "value": "NF-EXPORT" }
       ]
      },
      {
       "alias": "Option data dropped",
       "measurement": "Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter",
       "select": [
        [
         {
          "params": [
           "statistic/collector/option_data_dropped"
          ],
          "type": "field"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "exporter_name", "operator": "=", "value": "NF-EXPORT" }
       ]
      },
      {
       "alias": "Option templates dropped",
       "measurement": "Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter",
       "select": [
        [
         {
          "params": [
           "statistic/collector/templates_dropped"
          ],
          "type": "field"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "exporter_name", "operator": "=", "value": "NF-EXPORT" }
       ]
      },
      {
       "alias": "Packets dropped",
       "measurement": "Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter",
       "select": [
        [
         {
          "params": [
           "statistic/collector/packets_dropped"
          ],
          "type": "field"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "exporter_name", "operator": "=", "value": "NF-EXPORT" }
       ]
      }
     ]
    },
    {
     "title": "Netflow Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "alias": "Total export (bps)",
       "measurement": "Cisco-IOS-XR-ofa-netflow-oper:net-flow/statistics/statistic/server/flow-exporters/flow-exporter/exporter",
       "select": [
        [
         {
          "params": [
           "statistic/collector/last_minute_bytes_sent"
          ],
          "type": "field"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "* 8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "exporter_name", "operator": "=", "value": "NF-EXPORT" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "QoS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "QoS counters TRANSIT-1 (match rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "alias": "Class [[tag_class_stats/class_name]]",
       "groupBy": [
        { "params": [ "class_stats/class_name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/input/service-policy-names/service-policy-instance/statistics",
       "select": [
        [
         {
          "params": [
           "class_stats/general_stats/match_data_rate"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "service_policy_name", "operator": "=", "value": "RATE-LIMIT-DDOS" },
        { "condition": "AND", "key": "interface_name", "operator": "=", "value": "FourHundredGigE0/0/0/26" }
       ]
      }
     ]
    },
    {
     "title": "QoS counters TRANSIT-1 (drop rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "targets": [
      {
       "alias": "Class [[tag_class_stats/class_name]]",
       "groupBy": [
        { "params": [ "class_stats/class_name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/input/service-policy-names/service-policy-instance/statistics",
       "select": [
        [
         {
          "params": [
           "class_stats/general_stats/total_drop_rate"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "service_policy_name", "operator": "=", "value": "RATE-LIMIT-DDOS" },
        { "condition": "AND", "key": "interface_name", "operator": "=", "value": "FourHundredGigE0/0/0/26" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "URPF and RTBH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CEF Drops (pps)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "alias": "No route drops",
       "measurement": "Cisco-IOS-XR-fib-common-oper:fib-statistics/nodes/node/drops",
       "select": [
        [
         { "params": [ "no_route_packets" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
       ]
      },
      {
       "alias": "RPF drops",
       "measurement": "Cisco-IOS-XR-fib-common-oper:fib-statistics/nodes/node/drops",
       "select": [
        [
         { "params": [ "rpf_check_failure_packets" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
       ]
      },
      {
       "alias": "Null0 drops",
       "measurement": "Cisco-IOS-XR-fib-common-oper:fib-statistics/nodes/node/drops",
       "select": [
        [
         { "params": [ "null_packets" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "FIB Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "IPv4 prefixes distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "prefix_masklen_distribution/unicast_prefix/mask_length"
       ],
       "type": "tag"
      }
     ],
     "measurement": "Cisco-IOS-XR-fib-common-oper:fib/nodes/node/protocols/protocol/fib-summaries/fib-summary",
     "query": "SELECT last(\"prefix_masklen_distribution/unicast_prefix/number_of_prefixes\") FROM \"Cisco-IOS-XR-fib-common-oper:fib/nodes/node/protocols/protocol/fib-summaries/fib-summary\" WHERE (\"source\" = '8812-1' AND \"node_name\" = '0/RP0/CPU0' AND \"protocol_name\" = 'ipv4' AND \"vrf_name\" = 'default') AND $timeFilter GROUP BY \"prefix_masklen_distribution/unicast_prefix/mask_length\"",
     "select": [
      [
       {
        "params": [
         "prefix_masklen_distribution/unicast_prefix/number_of_prefixes"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "8812-1" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" },
      { "condition": "AND", "key": "protocol_name", "operator": "=", "value": "ipv4" },
      { "condition": "AND", "key": "vrf_name", "operator": "=", "value": "default" }
     ]
    }
   ]
  },
  {
   "title": "IPv6 prefixes distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "prefix_masklen_distribution/unicast_prefix/mask_length"
       ],
       "type": "tag"
      }
     ],
     "measurement": "Cisco-IOS-XR-fib-common-oper:fib/nodes/node/protocols/protocol/fib-summaries/fib-summary",
     "select": [
      [
       {
        "params": [
         "prefix_masklen_distribution/unicast_prefix/number_of_prefixes"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "8812-1" },
      { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" },
      { "condition": "AND", "key": "protocol_name", "operator": "=", "value": "ipv6" },
      { "condition": "AND", "key": "vrf_name", "operator": "=", "value": "default" }
     ]
    }
   ]
  },
  {
   "title": "System CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "System CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
       "select": [
        [
         { "params": [ "total_cpu_one_minute" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
       ]
      }
     ]
    },
    {
     "title": "System Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "Total Memory",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
       "select": [
        [
         { "params": [ "system_ram_memory" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
       ]
      },
      {
       "alias": "Free Memory",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
       "select": [
        [
         { "params": [ "free_physical_memory" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
       ]
      }
     ]
    },
    {
     "title": "BGP process CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
       "select": [
        [
         { "params": [ "total_cpu_one_minute" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" }
       ]
      }
     ]
    },
    {
     "title": "BGP process Memory Utilization",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XR-procmem-oper:processes-memory/nodes/node/process-ids/process-id",
       "select": [
        [
         { "params": [ "physical_mem" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/RP0/CPU0" },
        { "condition": "AND", "key": "process_id", "operator": "=", "value": "10996" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "BGP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of BGP Paths",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "alias": "$tag_af_name",
       "groupBy": [
        { "params": [ "af_name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/afs/af/af-process-info",
       "select": [
        [
         { "params": [ "global/local_paths_num" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" },
        { "condition": "AND", "key": "instance_name", "operator": "=", "value": "default" }
       ]
      }
     ]
    },
    {
     "title": "BGP updates per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "alias": "[[tag_neighbor_address]]",
       "query": "SELECT derivative(\"message_statistics/update/rx/count\", 1s) FROM \"Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/default-vrf/neighbors/neighbor\" WHERE (\"source\" = '8201-32FH') AND $timeFilter GROUP BY \"neighbor_address\""
      }
     ]
    },
    {
     "title": "IPv4 accepted prefixes per peer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "alias": "[[tag_neighbor_address]]",
       "groupBy": [
        { "params": [ "neighbor_address" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oc-oper:oc-bgp/bgp-rib/afi-safi-table/ipv4-unicast/open-config-neighbors/open-config-neighbor/adj-rib-in-post/num-routes",
       "select": [
        [
         { "params": [ "num_routes" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" }
       ]
      }
     ]
    },
    {
     "title": "IPv6 accepted prefixes per peer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "alias": "[[tag_neighbor_address]]",
       "groupBy": [
        { "params": [ "neighbor_address" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oc-oper:oc-bgp/bgp-rib/afi-safi-table/ipv6-unicast/open-config-neighbors/open-config-neighbor/adj-rib-in-post/num-routes",
       "select": [
        [
         { "params": [ "num_routes" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "LPM Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cisco 8000 LPM TCAM hardware usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "alias": "[[tag_npu_hwr/bank/bank_name]] - NPU[[tag_npu_hwr/npu_id]]",
       "groupBy": [
        { "params": [ "npu_hwr/bank/bank_name" ], "type": "tag" },
        { "params": [ "npu_hwr/npu_id" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-8000-platforms-npu-resources-oper:hw-resources-datas/hw-resources-data",
       "select": [
        [
         {
          "params": [
           "npu_hwr/bank/counter/inuse_entries"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8812-1" },
        { "condition": "AND", "key": "resource", "operator": "=", "value": "lpm-tcam" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/1/CPU0" }
       ]
      },
      {
       "alias": "8201-32FH [[tag_npu_hwr/bank/bank_name]] - NPU[[tag_npu_hwr/npu_id]]",
       "groupBy": [
        { "params": [ "npu_hwr/bank/bank_name" ], "type": "tag" },
        { "params": [ "npu_hwr/npu_id" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-8000-platforms-npu-resources-oper:hw-resources-datas/hw-resources-data",
       "query": "SELECT \"npu_hwr/bank/counter/inuse_entries\" FROM \"Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-8000-platforms-npu-resources-oper:hw-resources-datas/hw-resources-data\" WHERE (\"source\" = '8201-32FH' AND \"resource\" = 'lpm-tcam' AND \"node_name\" = '0/RP0/CPU0') AND $timeFilter GROUP BY \"npu_hwr/bank/bank_name\", \"npu_hwr/npu_id\"",
       "select": [
        [
         {
          "params": [
           "npu_hwr/bank/counter/inuse_entries"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8812-1" },
        { "condition": "AND", "key": "resource", "operator": "=", "value": "lpm-tcam" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/1/CPU0" }
       ]
      }
     ]
    },
    {
     "title": "8000 LPM TCAM resources utilization",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-8000-platforms-npu-resources-oper:hw-resources-datas/hw-resources-data",
       "query": "SELECT \"npu_hwr/bank/counter/inuse_entries\" FROM \"Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-8000-platforms-npu-resources-oper:hw-resources-datas/hw-resources-data\" WHERE (\"source\" = '8201-32FH' AND \"node_name\" = '0/RP0/CPU0' AND \"resource\" = 'lpm-tcam' AND \"npu_hwr/npu_id\" = '0' AND \"npu_hwr/bank/bank_name\" = 'lpm_tcam') AND $timeFilter",
       "select": [
        [
         {
          "params": [
           "npu_hwr/bank/counter/inuse_entries"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8812-1" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/1/CPU0" },
        { "condition": "AND", "key": "resource", "operator": "=", "value": "lpm-tcam" },
        { "condition": "AND", "key": "npu_hwr/npu_id", "operator": "=", "value": "0" },
        { "condition": "AND", "key": "npu_hwr/bank/bank_name", "operator": "=", "value": "lpm_tcam" }
       ]
      }
     ]
    },
    {
     "title": "8000 v4LPM TCAM resources utilization",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "entries" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-8000-platforms-npu-resources-oper:hw-resources-datas/hw-resources-data",
       "query": "SELECT last(\"npu_hwr/bank/counter/inuse_entries\") FROM \"Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-8000-platforms-npu-resources-oper:hw-resources-datas/hw-resources-data\" WHERE (\"source\" = '8201-32FH' AND \"node_name\" = '0/RP0/CPU0' AND \"npu_hwr/bank/bank_name\" = 'v4_lpm') AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         {
          "params": [
           "npu_hwr/bank/counter/inuse_entries"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8812-1" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/1/CPU0" },
        { "condition": "AND", "key": "npu_hwr/bank/bank_name", "operator": "=", "value": "v4_lpm" }
       ]
      }
     ]
    },
    {
     "title": "8000 v6LPM TCAM resources utilization",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "entries" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-8000-platforms-npu-resources-oper:hw-resources-datas/hw-resources-data",
       "query": "SELECT last(\"npu_hwr/bank/counter/inuse_entries\") FROM \"Cisco-IOS-XR-platforms-ofa-oper:ofa/stats/nodes/node/Cisco-IOS-XR-8000-platforms-npu-resources-oper:hw-resources-datas/hw-resources-data\" WHERE (\"source\" = '8201-32FH' AND \"npu_hwr/bank/bank_name\" = 'v6_lpm' AND \"node_name\" = '0/RP0/CPU0') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         {
          "params": [
           "npu_hwr/bank/counter/inuse_entries"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8812-1" },
        { "condition": "AND", "key": "npu_hwr/bank/bank_name", "operator": "=", "value": "v6_lpm" },
        { "condition": "AND", "key": "node_name", "operator": "=", "value": "0/1/CPU0" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPKI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPKI Telemetry",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "alias": "IPv4 ROA networks",
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/rpki-summary",
       "select": [
        [
         { "params": [ "ipv4roa_nets" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" }
       ]
      },
      {
       "alias": "IPv4 ROA paths",
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/rpki-summary",
       "select": [
        [
         { "params": [ "ipv4roa_paths" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" }
       ]
      },
      {
       "alias": "IPv6 ROA networks",
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/rpki-summary",
       "select": [
        [
         { "params": [ "ipv6roa_nets" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" }
       ]
      },
      {
       "alias": "IPv6 ROA paths",
       "measurement": "Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-active/rpki-summary",
       "select": [
        [
         { "params": [ "ipv6roa_paths" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "8201-32FH" }
       ]
      }
     ]
    }
   ]
  }
 ]
}