version: "2"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=netadmin
      - GF_SECURITY_ADMIN_PASSWORD=C1sco12345!
      - INFLUX_DB_TOKEN=C1sco12345!

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_USERNAME=netadmin
      - DOCKER_INFLUXDB_INIT_PASSWORD=C1sco12345!
      - DOCKER_INFLUXDB_INIT_ORG=lab
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=C1sco12345!
    volumes:
      - /tmp/influxdb2_data:/var/lib/influxdb2

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    ports:
      - '57500:57500'
    volumes:
     - ./telegraf_dial_out.conf:/etc/telegraf/telegraf.conf:ro
     #- ./telegraf_dial_in.conf:/etc/telegraf/telegraf.conf:ro
     #- ./embedded_tag.star:/etc/telegraf/embedded_tag.star:ro
